const CarauselConfig = {
	CSS_ANIMATION_DELAY: 10,
	DRAG_MULTIPLIER: 0.15,
	EDGE_THRESHOLD: 1,
	FRICTION: 0.96,
	MIN_VELOCITY: 0.5,
	OVERDRAG_PERCENTAGE: 0.018,
	OVERDRAG_RESET_DELAY: 50,
	SCROLL_SPEED: 0.5,
	SLINGSHOT_ANIMATION_DURATION: 400,
	SPRING_ANIMATION_DURATION: 200,
	TRANSITION_DELAY: 100,
	WHEEL_MULTIPLIER: 0.05,
} as const;

export { CarauselConfig };
