const RoutesValidationRule = {
	CATEGORY_MAXIMUM_LENGTH: 32,
	CATEGORY_MINIMUM_LENGTH: 4,
	DESCRIPTION_MAXIMUM_LENGTH: 8000,
	DESCRIPTION_MINIMUM_LENGTH: 10,
	MIN_PAGE: 1,
	MIN_PER_PAGE: 1,
	NAME_MAXIMUM_LENGTH: 32,
	NAME_MINIMUM_LENGTH: 4,
	REQUEST_MAX_POINTS_OF_INTEREST: 25,
	REQUEST_MIN_POINTS_OF_INTEREST: 2,
	ROUTES_MINIMUM_COUNT: 2,
	SEARCH_NAME_MINIMUM_LENGTH: 1,
} as const;

export { RoutesValidationRule };
