const RoutesValidationRule = {
	DESCRIPTION_MAXIMUM_LENGTH: 255,
	DESCRIPTION_MINIMUM_LENGTH: 10,
	NAME_MAXIMUM_LENGTH: 32,
	NAME_MINIMUM_LENGTH: 4,
	REQUEST_MAX_POINTS_OF_INTEREST: 25,
	REQUEST_MIN_POINTS_OF_INTEREST: 2,
	ROUTES_MINIMUM_COUNT: 2,
} as const;

export { RoutesValidationRule };
