const CENTRAL_PARK_LONGITUDE = -73.9654;
const CENTRAL_PARK_LATITUDE = 40.7829;

const DEFAULT_MAP_CENTER: [number, number] = [
	CENTRAL_PARK_LONGITUDE,
	CENTRAL_PARK_LATITUDE,
];
const DEFAULT_MAP_ZOOM = 12;
const DEFAULT_ROUTE_WIDTH = 4;
const DEFAULT_ROUTE_OPACITY = 0.8;
const DEFAULT_ROUTE_COLOR = "#3b82f6";
const DEFAULT_MARKER_COLOR = "#3b82f6";
const POPUP_OFFSET = 25;

const MAPBOX_STYLE_URL = "mapbox://styles/mapbox/streets-v12";
const MAPBOX_WALKING_PROFILE = "walking";
const MAPBOX_DIRECTIONS_BASE_URL =
	"https://api.mapbox.com/directions/v5/mapbox";

const NEXT_POI_INDEX_OFFSET = 1;
const ROUTE_COORDINATE_SLICE_START = 1;
const MINIMUM_COORDINATES_FOR_ROUTE = 1;

export {
	DEFAULT_MAP_CENTER,
	DEFAULT_MAP_ZOOM,
	DEFAULT_MARKER_COLOR,
	DEFAULT_ROUTE_COLOR,
	DEFAULT_ROUTE_OPACITY,
	DEFAULT_ROUTE_WIDTH,
	MAPBOX_DIRECTIONS_BASE_URL,
	MAPBOX_STYLE_URL,
	MAPBOX_WALKING_PROFILE,
	MINIMUM_COORDINATES_FOR_ROUTE,
	NEXT_POI_INDEX_OFFSET,
	POPUP_OFFSET,
	ROUTE_COORDINATE_SLICE_START,
};
