import { DEFAULT_POSITION } from "~/libs/constants/constants.js";

const DEFAULT_LOCATION_ZOOM = 15;
const DEFAULT_FLY_TO_DURATION = 2000;
const DEFAULT_RESIZE_DELAY = 100;
const DEFAULT_FALLBACK_ZOOM = 2;

const MAP_DEFAULTS = {
	CENTER: [DEFAULT_POSITION.LONGITUDE, DEFAULT_POSITION.LATITUDE] as [
		number,
		number,
	],
	CURRENT_POSITION_COLOR: "hsl(162deg 91% 25% / 100%)",
	FALLBACK_CENTER: [0, 0] as [number, number],
	FALLBACK_ZOOM: DEFAULT_FALLBACK_ZOOM,
	FLY_TO_DURATION: DEFAULT_FLY_TO_DURATION,
	IS_LOCATION_CONTROL: true,
	IS_MAP_CONTROL: true,
	IS_POI_LAYER: true,
	IS_SCALE_CONTROL: true,
	IS_SHOW_COMPASS: true,
	IS_TRACK_USER_LOCATION: false,
	IS_ZOOM_CONTROL: true,
	LOCATION_CONTROL_POSITION: "bottom-right" as const,
	LOCATION_ZOOM: DEFAULT_LOCATION_ZOOM,
	RESIZE_DELAY: DEFAULT_RESIZE_DELAY,
	SCALE_CONTROL_POSITION: "bottom-left" as const,
	SCALE_CONTROL_UNIT: "metric" as const,
	STYLE: "mapbox://styles/mapbox/streets-v12",
	ZOOM: 12,
	ZOOM_CONTROL_POSITION: "top-right" as const,
} as const;

export { MAP_DEFAULTS };
