import { type Marker } from "./libs/types/types.js";

const COORDINATES = {
	FEOFANIYA_LAKE: {
		LATITUDE: 50.346_049,
		LONGITUDE: 30.489_361,
	},
	GLASS_BRIDGE: {
		LATITUDE: 50.455_258,
		LONGITUDE: 30.528_915,
	},
	PARK_LANDSCAPE_ALLEY: {
		LATITUDE: 50.456_445,
		LONGITUDE: 30.512_19,
	},
	PLYAZH_TROESHCHYNA: {
		LATITUDE: 50.504_872,
		LONGITUDE: 30.568_354,
	},
	RIVER_GRILL: {
		LATITUDE: 50.435_812,
		LONGITUDE: 30.591_645,
	},
	SUP_KAYAK_CLUB: {
		LATITUDE: 50.495_673,
		LONGITUDE: 30.547_75,
	},
} as const;

const MOCK_MARKERS: Marker[] = [
	[COORDINATES.SUP_KAYAK_CLUB.LONGITUDE, COORDINATES.SUP_KAYAK_CLUB.LATITUDE],
	[COORDINATES.RIVER_GRILL.LONGITUDE, COORDINATES.RIVER_GRILL.LATITUDE],
	[COORDINATES.FEOFANIYA_LAKE.LONGITUDE, COORDINATES.FEOFANIYA_LAKE.LATITUDE],
	[COORDINATES.GLASS_BRIDGE.LONGITUDE, COORDINATES.GLASS_BRIDGE.LATITUDE],
	[
		COORDINATES.PARK_LANDSCAPE_ALLEY.LONGITUDE,
		COORDINATES.PARK_LANDSCAPE_ALLEY.LATITUDE,
	],
	[
		COORDINATES.PLYAZH_TROESHCHYNA.LONGITUDE,
		COORDINATES.PLYAZH_TROESHCHYNA.LATITUDE,
	],
];

export { MOCK_MARKERS };
