import { TIME_UNIT } from "~/libs/constants/constants.js";

const DEFAULT_TIMEOUT_SECONDS = 15;

const DEFAULT_POSITION_OPTIONS = {
	ENABLE_HIGH_ACCURACY: true,
	MAXIMUM_AGE: TIME_UNIT.SECONDS_IN_MINUTE * TIME_UNIT.MILLISECONDS_IN_SECOND,
	TIMEOUT: DEFAULT_TIMEOUT_SECONDS * TIME_UNIT.MILLISECONDS_IN_SECOND,
};

const DEFAULT_POSITION = {
	LATITUDE: 50.4501,
	LONGITUDE: 30.5234,
};

export { DEFAULT_POSITION, DEFAULT_POSITION_OPTIONS };
