const DEFAULT_POSITION_OPTIONS = {
	ENABLE_HIGH_ACCURACY: true,
	MAXIMUM_AGE: 60 * 1000,
	TIMEOUT: 15 * 1000,
};

const DEFAULT_POSITION = {
	LATITUDE: 50.4501,
	LONGITUDE: 30.5234,
};

export {
	DEFAULT_POSITION,
	DEFAULT_POSITION_OPTIONS,
};
