const SECONDS_IN_MINUTE = 60;
const MILLISECONDS_IN_SECOND = 1000;
const DEFAULT_TIMEOUT_SECONDS = 15;

const DEFAULT_POSITION_OPTIONS = {
	ENABLE_HIGH_ACCURACY: true,
	MAXIMUM_AGE: SECONDS_IN_MINUTE * MILLISECONDS_IN_SECOND,
	TIMEOUT: DEFAULT_TIMEOUT_SECONDS * MILLISECONDS_IN_SECOND,
};

const DEFAULT_POSITION = {
	LATITUDE: 50.4501,
	LONGITUDE: 30.5234,
};

export { DEFAULT_POSITION, DEFAULT_POSITION_OPTIONS };
