const MAX_PASSWORD_LENGTH = 64;
const MIN_PASSWORD_LENGTH = 6;

const MAX_FIRSTNAME_LENGTH = 64;
const MIN_FIRSTNAME_LENGTH = 2;

const MAX_LASTNAME_LENGTH = 64;
const MIN_LASTNAME_LENGTH = 2;

const NUMBER_1 = 1;
const NUMBER_36 = 36;
const NUMBER_2 = 2;
const NUMBER_6 = 6;
export {
	MAX_FIRSTNAME_LENGTH,
	MAX_LASTNAME_LENGTH,
	MAX_PASSWORD_LENGTH,
	MIN_FIRSTNAME_LENGTH,
	MIN_LASTNAME_LENGTH,
	MIN_PASSWORD_LENGTH,
	NUMBER_1,
	NUMBER_2,
	NUMBER_6,
	NUMBER_36,
};
