const UserValidationRule = {
	BANNED_EMAIL_DOMAINS: [".ru"],
	EMAIL_MINIMUM_LENGTH: 6,
	FIRST_NAME_MINIMUM_LENGTH: 2,
	LAST_NAME_MINIMUM_LENGTH: 2,
	MAX_LENGTH: 64,
	PASSWORD_MINIMUM_LENGTH: 6,
	REQUIRED_STRING_MIN_LENGTH: 1,
} as const;

export { UserValidationRule };
