const UserValidationRule = {
	EMAIL_MINIMUM_LENGTH: 6,
	FIRST_NAME_MINIMUM_LENGTH: 2,
	LAST_NAME_MINIMUM_LENGTH: 2,
	PASSWORD_MINIMUM_LENGTH: 6,
	REQUIRED_STRING_MIN_LENGTH: 1,
	STRING_MAX_LENGTH: 64,
} as const;

export { UserValidationRule };
