const DEFAULT_LATITUDE = 50.4501;
const DEFAULT_LONGITUDE = 30.5234;

const MAP_PARAMETERS = {
	AUTO_TRIGGER_DELAY: 100,
	BEFORE_LOAD_DELAY: 500,
	CONTAINER_RETRY_DELAY: 100,
	COORDINATE_ARRAY_LENGTH: 2,
	DEFAULT_CENTER: [DEFAULT_LONGITUDE, DEFAULT_LATITUDE],
	DEFAULT_ZOOM: 12,
	LOCATION_ZOOM: 15,
	MAP_STYLE: "mapbox://styles/mapbox/streets-v12",
	RESIZE_TIMEOUT: 100,
};

export { MAP_PARAMETERS };
